madcoders_rma_admin_order_return:
  resource: |
    alias: madcoders_rma.order_return
    section: admin
    only: [index, update, delete, bulkDelete]
    templates: "@SyliusAdmin\\Crud"
    redirect: index
    grid: madcoders_rma_admin_return_orders
    vars:
        all:
            subheader: madcoders_rma.ui.mainslider
        index:
            icon: 'file dolly outline'
  type: sylius.resource
