madcoders_rma_admin_order_return:
  resource: |
    alias: madcoders_rma.order_return
    section: admin
    only: [index, update, delete, bulkDelete]
    templates: "@SyliusAdmin\\Crud"
    redirect: index
    grid: madcoders_rma_admin_return_orders
    vars:
        all:
            subheader: madcoders_rma.ui.return_list
        index:
            icon: 'file dolly outline'
  type: sylius.resource

madcoders_rma_admin_order_return_show:
  path: /order-returns/{id}
  methods: [ GET, POST ]
  controller: madcoders.sylius_rma_plugin.controller.admin_management_controller:viewIndex
  defaults:
    template: "@MadcodersSyliusRmaPlugin/Admin/Return/show.html.twig"
    _sylius:
      section: admin
      permission: true
      repository:
        arguments:
          - $id
