madcoders_rma_admin_order_return:
    resource: |
        alias: madcoders_rma.order_return
        section: admin
        only: [index, update, delete, bulkDelete]
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: madcoders_rma_admin_return_orders
        vars:
            all:
                subheader: madcoders_rma.ui.return_list
            index:
                icon: 'file dolly outline'
    type: sylius.resource

madcoders_rma_admin_order_return_reason:
  resource: |
    alias: madcoders_rma.order_return_reason
    section: admin
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: madcoders_rma_admin_return_reason
    vars:
        all:
            subheader: madcoders_rma.ui.return_reason_list
            templates:
                form: "@MadcodersSyliusRmaPlugin/Admin/Reason/_form.html.twig"
        index:
            icon: 'edit outline'
  type: sylius.resource

madcoders_rma_admin_order_return_consent:
  resource: |
    alias: madcoders_rma.order_return_consent
    section: admin
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: madcoders_rma_admin_return_consent
    vars:
        all:
            subheader: madcoders_rma.ui.order_return_consent_subheader
            templates:
                form: "@MadcodersSyliusRmaPlugin/Admin/Consent/_form.html.twig"
        index:
            icon: 'briefcase'
  type: sylius.resource

madcoders_rma_admin_order_return_config_edit:
  path: /rma-configuration/{channelId}
  methods: [ GET, POST ]
  controller: madcoders.sylius_rma_plugin.controller.rma_configuration_controller:viewIndex
  defaults:
    channelId: null
    template: "@MadcodersSyliusRmaPlugin/Admin/Configuration/show.html.twig"
    _sylius:
      section: admin
      permission: true
      repository:
        arguments:
          - $channelId

madcoders_rma_admin_order_return_config_change_channel:
  path: /rma-configuration-change-channel
  methods: [ POST ]
  controller: madcoders.sylius_rma_plugin.controller.rma_configuration_controller:changeChannel
  defaults:
    _sylius:
      redirect: madcoders_rma_admin_order_return_config_edit
      section: admin
      permission: true

madcoders_rma_admin_order_return_config_add_address_to_selected_channel:
  path: /rma-configuration-change-channel/{channelId}
  methods: [ POST ]
  controller: madcoders.sylius_rma_plugin.controller.rma_configuration_controller:saveAddressToSelectedChannel
  defaults:
    template: "@MadcodersSyliusRmaPlugin/Admin/Configuration/show.html.twig"
    _sylius:
      redirect: madcoders_rma_admin_order_return_config_edit
      section: admin
      permission: true

madcoders_rma_admin_order_return_show:
  path: /order-returns/{id}
  methods: [ GET, POST ]
  controller: madcoders.sylius_rma_plugin.controller.admin_management_controller:viewIndex
  defaults:
    template: "@MadcodersSyliusRmaPlugin/Admin/Return/show.html.twig"
    _sylius:
      section: admin
      permission: true
      repository:
        arguments:
          - $id

madcoders_rma_admin_order_return_show_cancel:
  path: /order-returns/{id}/cancel/{_csrf_token}
  methods: [ GET ]
  controller: madcoders_rma.controller.order_return:applyStateMachineTransitionAction
  defaults:
    _sylius:
      section: admin
      permission: true
      flash: madcoders.admin.history.cancelled_return
      repository:
        method: findOneById
        arguments:
          - $id
      state_machine:
        graph: return_status
        transition: cancel

madcoders_rma_admin_order_return_show_complete:
  path: /order-returns/{id}/complete/{_csrf_token}
  methods: [ GET ]
  controller: madcoders_rma.controller.order_return:applyStateMachineTransitionAction
  defaults:
    _sylius:
      section: admin
      permission: true
      flash: madcoders.admin.history.completed_return
      repository:
        method: findOneById
        arguments:
          - $id
      state_machine:
        graph: return_status
        transition: complete
