madcoders_rma_start:
    path: /rma-start
    methods: [ GET, POST ]
    controller: madcoders.sylius_rma_plugin.controller.auth_controller:start
    defaults:
        template: '@MadcodersSyliusRmaPlugin/Auth/start.html.twig'
        _sylius:
            error_redirect: madcoders_rma_start
            redirect: madcoders_rma_verification

madcoders_rma_verification:
    path: /rma-start/{code}
    methods: [ GET, POST ]
    controller: madcoders.sylius_rma_plugin.controller.auth_controller:verification
    defaults:
        template: '@MadcodersSyliusRmaPlugin/Auth/verification.html.twig'
        _sylius:
            error_redirect: madcoders_rma_verification
            redirect: madcoders_rma_return_form
            repository:
                method: findOneByCode
                arguments:
                    - $code

madcoders_rma_return_form:
    path: /rma-form
    methods: [ GET, POST ]
    controller: madcoders.sylius_rma_plugin.controller.return_controller:viewIndex
    defaults:
        template: '@MadcodersSyliusRmaPlugin/Return/view.html.twig'
        _sylius:
            error_redirect: madcoders_rma_verification
            redirect: sylius_shop_homepage

madcoders_rma_return_form_accept:
    path: /rma-summary/{returnNumber}
    methods: [ GET, POST ]
    controller: madcoders.sylius_rma_plugin.controller.return_controller:acceptIndex
    defaults:
        template: '@MadcodersSyliusRmaPlugin/Return/summary.html.twig'
        _sylius:
            repository:
                arguments:
                    - $returnNumber

madcoders_rma_return_form_success:
    path: /rma-success/{returnNumber}
    methods: [ GET ]
    controller: madcoders.sylius_rma_plugin.controller.return_controller:successIndex
    defaults:
        template: '@MadcodersSyliusRmaPlugin/Return/success.html.twig'
        _sylius:
            repository:
                arguments:
                    - $returnNumber

madcoders_rma_return_form_print:
    path: /rma-form-print/{returnNumber}
    methods: [ GET ]
    controller: madcoders.sylius_rma_plugin.controller.return_controller:printIndex
    defaults:
        template: '@MadcodersSyliusRmaPlugin/Return/success.html.twig'
        _sylius:
            repository:
                arguments:
                    - $returnNumber
