#
# This file is part of package:
# Sylius RMA Plugin
#
# @copyright MADCODERS Team (www.madcoders.co)
# @licence For the full copyright and license information, please view the LICENSE
#
# Architects of this package:
# @author Leonid Moshko <l.moshko@madcoders.pl>
# @author Piotr Lewandowski <p.lewandowski@madcoders.pl>
#
sylius_grid:
    templates:
        action:
            madcoders_rma_create_new: "@MadcodersSyliusRmaPlugin/BulkAction/createNewReturn.html.twig"
    grids:
        sylius_shop_account_order:
            actions:
                item:
                    madcoders_rma_create_new:
                        type: madcoders_rma_create_new
                        label: madcoders_rma.ui.action.create_new_return
                        options:
                            link:
                                route: madcoders_rma_shop_account_create_new_return
                                parameters:
                                    orderNumber: resource.number
