#
# This file is part of package:
# Sylius RMA Plugin
#
# @copyright MADCODERS Team (www.madcoders.co)
# @licence For the full copyright and license information, please view the LICENSE
#
# Architects of this package:
# @author Leonid Moshko <l.moshko@madcoders.pl>
# @author Piotr Lewandowski <p.lewandowski@madcoders.pl>
#
sylius_grid:
  grids:
    madcoders_rma_admin_return_orders:
      driver:
        name: doctrine/orm
        options:
          class: Madcoders\SyliusRmaPlugin\Entity\OrderReturn
      sorting:
        date: desc
      fields:
        date:
          type: datetime
          label: sylius.ui.date
          path: createdAt
          sortable: createdAt
          options:
            format: d-m-Y H:i:s
        returnNumber:
          type: string
          label: madcoders_rma.ui.return_number
        channel:
          path: channelCode
          type: twig
          label: sylius.ui.channel
          sortable: channelCode
          options:
            template: "@MadcodersSyliusRmaPlugin/Admin/Return/Grid/Field/channel.html.twig"
        number:
          path: orderNumber
          type: twig
          label: madcoders_rma.ui.order_number
          sortable: ~
          options:
            template: "@MadcodersSyliusRmaPlugin/Admin/Return/Grid/Field/number.html.twig"
        customer:
          path: .
          type: twig
          label: sylius.ui.customer
          sortable: lastName
          options:
            template: "@MadcodersSyliusRmaPlugin/Admin/Return/Grid/Field/customer.html.twig"
        orderReturnStatus:
          type: twig
          label: sylius.ui.state
          sortable: ~
          options:
            template: "@SyliusUi/Grid/Field/state.html.twig"
            vars:
              labels: "@MadcodersSyliusRmaPlugin/Admin/Return/Label/State"
      actions:
        item:
          show:
            type: show
