sylius_grid:
    templates:
        action:
            madcoders_rma_shop_download: "@MadcodersSyliusRmaPlugin/BulkAction/printReturnFormDownload.html.twig"
            madcoders_rma_shop_edit: "@MadcodersSyliusRmaPlugin/BulkAction/editReturn.html.twig"
    grids:
        madcoders_rma_shop_return_orders_grid:
            driver:
                name: doctrine/orm
                options:
                    class: Madcoders\SyliusRmaPlugin\Entity\OrderReturn
                    repository:
                        method: createReturnsListQueryBuilder
                        arguments:
                            customerEmail: 'expr:service("security.token_storage").getToken().getUser().getCustomer().getEmail()'
            sorting:
                createdAt: desc
            limits: [25, 50, 100]
            fields:
                createdAt:
                    type: datetime
                    label: sylius.ui.created
                    sortable: ~
                    options:
                        format: d-m-Y
                returnNumber:
                    type: string
                    label: madcoders_rma.ui.return_number
                    sortable: ~
                number:
                    path: orderNumber
                    type: twig
                    label: madcoders_rma.ui.order_number
                    sortable: ~
                    options:
                        template: "@MadcodersSyliusRmaPlugin/Shop/Return/Grid/Field/number.html.twig"
                orderReturnStatus:
                    type: twig
                    label: sylius.ui.state
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/state.html.twig"
                        vars:
                            labels: "@MadcodersSyliusRmaPlugin/Admin/Return/Label/State"
            actions:
                item:
                    show:
                        type: shop_show
                        label: sylius.ui.show
                        options:
                            link:
                                route: madcoders_rma_shop_account_return_order_show
                                parameters:
                                    returnNumber: resource.returnNumber
                    download:
                        type: madcoders_rma_shop_download
                        label: madcoders_rma.ui.success.print_order_return_form
                        options:
                            link:
                                route: madcoders_rma_shop_account_return_order_download
                                parameters:
                                    returnNumber: resource.returnNumber
                    edit:
                        type: madcoders_rma_shop_edit
                        label: madcoders_rma.ui.edit_form
                        options:
                            link:
                                route: madcoders_rma_shop_account_create_new_return
                                parameters:
                                    orderNumber: resource.orderNumber
