definitions:
    services:
        mysql:
            image: mysql:8.0
            variables:
                MYSQL_DATABASE: sylius_test
                MYSQL_ROOT_PASSWORD: root
    steps:
        - step: &setup
              name: "Install dependencies"
              image: php:8.2
              caches:
                  - composer
              script:
                  - apt-get update && apt-get install -y git unzip libicu-dev libzip-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev
                  - docker-php-ext-configure gd --with-freetype --with-jpeg
                  - docker-php-ext-install -j$(nproc) intl pdo_mysql zip gd
                  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --no-scripts
              artifacts:
                  - vendor/**
                  - tests/Application/**

image: php:8.2

pipelines:
    default:
        - step:
              <<: *setup
        - parallel:
              - step:
                    name: "Unit and component tests"
                    image: php:8.2
                    caches:
                        - composer
                    script:
                        - php vendor/bin/phpunit -c phpunit.xml.dist
              - step:
                    name: "Static analysis"
                    image: php:8.2
                    caches:
                        - composer
                    script:
                        - php vendor/bin/phpstan analyse -c phpstan.neon
                        - php vendor/bin/ecs check src
        - step:
              name: "Behat scenarios (non-JS)"
              image: php:8.2
              services:
                  - mysql
              caches:
                  - composer
              script:
                  - apt-get update && apt-get install -y libicu-dev libzip-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev
                  - docker-php-ext-configure gd --with-freetype --with-jpeg
                  - docker-php-ext-install -j$(nproc) intl pdo_mysql zip gd
                  - export APP_ENV=test
                  - export DATABASE_URL=mysql://root:root@127.0.0.1:3306/sylius_test?serverVersion=8.0
                  - (cd tests/Application && APP_ENV=test bin/console doctrine:database:create --if-not-exists --no-interaction)
                  - (cd tests/Application && APP_ENV=test bin/console doctrine:schema:create --no-interaction)
                  - vendor/bin/behat --strict --no-interaction --tags="~@javascript"
