imports:
  - { resource: "@MadcodersSyliusRmaPlugin/Resources/config/grids.yaml" }

sylius_mailer:
  emails:
    authcode_generated:
      subject: sylius.emails.authcode_generated.subject
      template: "@MadcodersSyliusRmaPlugin/Email/authCodeGenerated.html.twig"
    return_generated:
      subject: sylius.emails.return_generated.subject
      template: "@MadcodersSyliusRmaPlugin/Email/returnFormGenerated.html.twig"

sylius_ui:
  events:
    madcoders_rma.admin.order_return.show.content:
      blocks:
        before_header_legacy:
          template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
          priority: 35
          context:
            event: sylius.admin.order_return.show.before_header
        header:
          template: "@MadcodersSyliusRmaPlugin/Admin/Return/Show/_headerWidget.html.twig"
          priority: 30
        after_header_legacy:
          template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
          priority: 25
          context:
            event: sylius.admin.order_return.show.after_header
        breadcrumb:
          template: "@MadcodersSyliusRmaPlugin/Admin/Return/Show/_breadcrumb.html.twig"
          priority: 20
        after_breadcrumb_legacy:
          template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
          priority: 15
          context:
            event: sylius.admin.order_return.show.after_breadcrumb
        content:
          template: "@MadcodersSyliusRmaPlugin/Admin/Return/Show/_content.html.twig"
          priority: 10
        after_content_legacy:
          template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
          priority: 5
          context:
            event: sylius.admin.order.show.after_content

# order return state machine

winzou_state_machine:
  order_return:
    class: 'Madcoders\SyliusRmaPlugin\Entity\OrderReturn'
    graph: return_status
    property_path: orderReturnStatus
    state_machine_class: "%sylius.state_machine.class%"
    states:
      draft: ~
      new: ~
      completed: ~
      canceled: ~
    callbacks:
      after:
        updated_changelog_on_cancel:
          on: [ 'cancel' ]
          do: [ '@madcoders.sylius_rma_plugin.services.callbacks.updated_changelog_on_cancel', 'updatedChangelogOnCancel' ]
          args: [ 'object' ]
        updated_changelog_on_complete:
          on: [ 'complete' ]
          do: [ '@madcoders.sylius_rma_plugin.services.callbacks.updated_changelog_on_complete', 'UpdatedChangelogOnComplete' ]
          args: [ 'object' ]

    transitions:
      new:
        from: ['draft']
        to: new
      complete:
        from: ['new']
        to: completed
      cancel:
        from: ['draft', 'new']
        to: canceled

# HOW TO USE ORDER RETURN STATE MACHINE

#  $orderReturnStateMachine = $this->stateMachineFactory->get($orderReturn, OrderReturnInterface::GRAPH);
#    if (!$orderReturnStateMachine->can(OrderReturnInterface::TRANSITION_ACCEPT)) {
#       // just do nothign or throw exception depending on the situation
#       return;
#     }
#
#  $orderReturnStateMachine->apply(OrderReturnInterface::TRANSITION_ACCEPT));
#  $this->orderReturnRepository->add($orderReturn);
