#
# This file is part of package:
# Sylius RMA Plugin
#
# @copyright MADCODERS Team (www.madcoders.co)
# @licence For the full copyright and license information, please view the LICENSE
#
# Architects of this package:
# @author Leonid Moshko <l.moshko@madcoders.pl>
# @author Piotr Lewandowski <p.lewandowski@madcoders.pl>
#
imports:
    - { resource: "@MadcodersSyliusRmaPlugin/Resources/config/grids/madcoders_rma_admin_return_orders_grid.yml" }
    - { resource: "@MadcodersSyliusRmaPlugin/Resources/config/grids/madcoders_rma_admin_return_reason_grid.yml" }
    - { resource: "@MadcodersSyliusRmaPlugin/Resources/config/grids/madcoders_rma_admin_return_consent_grid.yml" }
    - { resource: "@MadcodersSyliusRmaPlugin/Resources/config/grids/madcoders_rma_shop_return_orders_grid.yml" }
    - { resource: "@MadcodersSyliusRmaPlugin/Resources/config/grids/madcoders_rma_shop_account_order_grid.yml" }
