sylius_resource:
  resources:
    madcoders.authcode:
      classes:
        model: Madcoders\SyliusRmaPlugin\Entity\AuthCode
        #repository: Madcoders\SyliusRmaPlugin\Repository\AuthCode

    madcoders.order_return:
      classes:
        model: Madcoders\SyliusRmaPlugin\Entity\OrderReturn
        #form: Madcoders\SyliusRmaPlugin\Form\OrderReturn
        #repository: Madcoders\SyliusRmaPlugin\Repository\OrderReturn

    madcoders.order_return_item:
      classes:
        model: Madcoders\SyliusRmaPlugin\Entity\OrderReturnItem
        #form: Madcoders\SyliusRmaPlugin\Form\OrderReturnItem
        #repository: Madcoders\SyliusRmaPlugin\Repository\OrderReturnItem
