#
# This file is part of package:
# Sylius RMA Plugin
#
# @copyright MADCODERS Team (www.madcoders.co)
# @licence For the full copyright and license information, please view the LICENSE
#
# Architects of this package:
# @author Leonid Moshko <l.moshko@madcoders.pl>
# @author Piotr Lewandowski <p.lewandowski@madcoders.pl>
#
madcoders_rma_shop:
    resource: "@MadcodersSyliusRmaPlugin/Resources/config/routing/shop_routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

madcoders_rma_admin:
    resource: "@MadcodersSyliusRmaPlugin/Resources/config/routing/admin_routing.yml"
    prefix: /admin

madcoders_rma_credits:
    path: /madcoders/rma/credits
    defaults:
        _controller: Madcoders\SyliusRmaPlugin\Controller\CreditsController
